### ISSUE TITLE
AI 수업 수강생입니다.

### ISSUE THREAD

**Issue by sdoggod** [rudvlf0413/skt-exercise#1]
진행했던 내용 중에 Doc2Vec 관련 reference code와 간단하게 설명된 자료 혹시 있으시면 공유 가능하실까요?ㅎ Doc2Vec에 관심이 있었는데, 실습 진행을 못한 것 같아서요!ㅎ 
항상 감사합니다!

**Comment by Kyeongpil** [comment]
@sdoggod 음 doc2vec은 언급이 없었는데 어떤 부분인지 자세히 말씀해주실 수 있으신가요??
rnn 모델 말씀하시는건지...

**Comment by sdoggod** [comment]
네! 수업시간에 훅 지나가긴 했는데, Word2Vec 뒷부분 슬라이드 보면 Doc2Vec 내용이 있는데, 그 부분 참고 자료와 샘플코드 공유해주시면 구현해보려고요.
저희 교재로는 주재걸 교수님의 "word Embedding" 슬라이드 뒷부분에 있습니다.
감사합니다.

**Comment by Kyeongpil** [comment]
아아 넵 논문으로는
https://cs.stanford.edu/~quocle/paragraph_vector.pdf을 보시면 될 것 같고
라이브러리는 저번에 소개해드린 Gensim에 doc2vec이 있습니다.
https://radimrehurek.com/gensim/models/doc2vec.html
이것들을 참조해보시면 될 것 같아요~

**Comment by sdoggod** [comment]
네! 감사합니다.
